name: "C++ CI"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: cmake .
      - run: cmake --build .
      - name: Run
        uses: GuillaumeFalourd/command-output-file-action@v1.1
        with:
          command_line: ./print_ip
          output_file_name: output.txt
          display_file_content: YES # this is also the default value if not informed
